spring.mail.host=smtp.gmail.com
spring.mail.port=
spring.mail.username=noreply.rulex@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

error.files.path=
excel.files.path=

host.dns=
